# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-15 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('head_description', models.TextField(blank=True, null=True)),
                ('head_bttn', models.CharField(default='Join ', max_length=30)),
                ('head_bttn_url', models.CharField(blank=True, max_length=40, null=True)),
                ('page_content', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
