# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-03 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20180721_0312'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='page',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
