# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-03 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20180803_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='slug',
            field=models.SlugField(default='page-slug'),
        ),
    ]
