# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-04 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20180804_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='leave_capture',
            field=models.BooleanField(default=True),
        ),
    ]
