# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-04 20:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_page_leave_capture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='leave_capture',
        ),
    ]
