# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-30 00:54
from __future__ import unicode_literals

from django.db import migrations, models
import pages.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_page_small_heading'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='small_heading',
        ),
        migrations.AddField(
            model_name='page',
            name='body_color',
            field=models.CharField(blank=True, default='#dddddd', max_length=7, null=True, validators=[pages.models.layout_validator]),
        ),
        migrations.AlterField(
            model_name='page',
            name='nav_color',
            field=models.CharField(blank=True, default='#ffffff', max_length=7, null=True, validators=[pages.models.layout_validator]),
        ),
    ]
