# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-01 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_auto_20181030_0254'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='image_bg',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='page',
            name='layout',
            field=models.CharField(choices=[('standard', 'Standard'), ('stacked', 'Stacked'), ('classic', 'Classic')], default='standard', max_length=20),
        ),
    ]
