# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-01 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_auto_20181101_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='head_bttn_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
